import { collection } from 'firebase/firestore'
import { db } from './config'

export const col = (name) => collection(db, name)

export const Collections = {
  INVENTORY: 'inventory',
  PROJECTS: 'projects',
  MAINTENANCE: 'maintenance',
  AMC: 'amc',
  AMC_MONTHLY: 'amcMonthlyMaintenance',
  EMPLOYEES: 'employees',
  USERS: 'users',
  ACTIVITIES: 'activities',
  LEADS: 'leads',
  TASKS: 'tasks',
  INVOICES: 'invoices',
  INSTALLATION: 'installationActivities',
  MODERNISATION: 'modernisationActivities',
  REPAIRS: 'repairActivities',
  COMPLAINTS: 'complaintActivities',
  SALARY_SLIPS: 'salarySlips',
  SALARY_CONFIG: 'salaryConfig',
  QUOTATIONS: 'quotations',
  PURCHASE_ORDERS: 'purchaseOrders',
  PROFORMA_INVOICES: 'proformaInvoices',
  TAX_INVOICES: 'taxInvoices',
  VENDORS: 'vendors',
  MATERIALS: 'materials',
  BOM: 'bom',
  SETTINGS: 'settings',
  LEAVE: 'leaveRequests',
  PROJECT_TIMELINE: 'projectTimeline',
  CONFIGURATIONS: 'configurations',
  GALLERY: 'gallery',
  GALLERY_FOLDERS: 'galleryFolders',
  INSPECTIONS: 'inspections',
  CHECKLIST_ITEMS: 'checklistItems',
  PDF_CACHE:  'pdfCache',
  FCM_TOKENS: 'fcmTokens',
  ATTENDANCE: 'attendance',
  TECHNICIAN_LOCATIONS: 'technicianLocations',
  SITE_VISIT_EVENTS: 'siteVisitEvents',
  TRACKING_SESSIONS: 'trackingSessions',
  LOCATION_HISTORY: 'locationHistory',
  INVENTORY_USAGE: 'inventoryUsage',
  ADMIN_OTPS: 'adminOtps',
  TICKETS: 'tickets',
  LIFT_CERTIFICATES: 'liftCertificates',
}
