import { useCompanyConfig } from '@/composables/useCompanyConfig'
import { useAuthStore } from '@/stores/auth'
import { Capacitor } from '@capacitor/core'
import { getAll } from '@/firebase/firestore'
import { Collections } from '@/firebase/collections'

// ── Page constants ───────────────────────────────────────────────────────────
const PAGE_W  = 210
const PAGE_H  = 297
const MARGIN  = 12

// ── Colour tokens (RGB arrays) ───────────────────────────────────────────────
const C = {
  blue:      [37,  99, 235],
  indigo:    [99, 102, 241],
  darkText:  [17,  24,  39],
  greyText:  [75,  85,  99],
  mutedText: [107, 114, 128],
  border:    [209, 213, 219],
  rowAlt:    [249, 250, 251],
  sectionBg: [241, 245, 249],
  white:     [255, 255, 255],
  red:       [220,  38,  38],
  green:     [22,  163,  74],
  amber:     [180,  83,   9],
  purple:    [99,  102, 241],
  // ── aliases for backward compat ──
  get black()     { return this.darkText },
  get darkGrey()  { return [55, 65, 81] },
  get midGrey()   { return this.mutedText },
  get lightGrey() { return this.rowAlt },
  get silver()    { return this.border },
  get accent()    { return this.indigo },
}

// ── Helpers ──────────────────────────────────────────────────────────────────
export function toRs(amount) {
  return `Rs. ${Number(amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function nowStrings() {
  const d = new Date()
  return {
    date: d.toLocaleDateString('en-IN',  { day: '2-digit', month: 'short', year: 'numeric' }),
    time: d.toLocaleTimeString('en-IN',  { hour: '2-digit', minute: '2-digit' }),
  }
}

function fitText(doc, text, maxW) {
  // Truncate or wrap — returns a string that fits in maxW mm
  let s = String(text || '')
  while (s.length > 4 && doc.getTextWidth(s) > maxW) s = s.slice(0, -4) + '…'
  return s
}

// ── Static logo cache (loaded once from /static/logo.png) ───────────────────
let _cachedLogoDataUrl = null
let _logoLoadAttempted = false

async function getStaticLogoDataUrl() {
  if (_cachedLogoDataUrl !== null) return _cachedLogoDataUrl
  if (_logoLoadAttempted) return null
  _logoLoadAttempted = true
  try {
    const res = await fetch('/static/logo.png')
    if (!res.ok) return null
    const blob = await res.blob()
    return await new Promise((resolve) => {
      const reader = new FileReader()
      reader.onload = () => { _cachedLogoDataUrl = reader.result; resolve(_cachedLogoDataUrl) }
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch { return null }
}

// ── Draw standard PDF header ─────────────────────────────────────────────────
// Returns Y where body content should start
export async function drawHeader(doc, { company, userName, title, subtitle, accent = C.blue }) {
  const [r, g, b] = accent
  const { date, time } = nowStrings()

  // ── Band 1: company identity (34 mm) ────────────────────────────────────
  doc.setFillColor(r, g, b)
  doc.rect(0, 0, PAGE_W, 34, 'F')

  // Logo: prefer /static/logo.png → company.logoUrl → initials badge
  let textX = MARGIN
  const staticLogo = await getStaticLogoDataUrl()
  const logoUrl = staticLogo || company.logoUrl || company.logo
  if (logoUrl) {
    try {
      const ext = logoUrl.includes('png') ? 'PNG' : 'JPEG'
      doc.addImage(logoUrl, ext, MARGIN, 5, 22, 22)
      textX = MARGIN + 26
    } catch (_) { /* fall through to initials */ }
  }
  if (textX === MARGIN) {
    // Initials badge — white box with accent border
    doc.setFillColor(255, 255, 255)
    doc.roundedRect(MARGIN, 6, 20, 20, 3, 3, 'F')
    const initials = (company.name || 'CO').split(' ').filter(Boolean).map(w => w[0]).slice(0, 2).join('').toUpperCase()
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(r, g, b)
    doc.text(initials, MARGIN + 10, 18, { align: 'center' })
    textX = MARGIN + 26
  }

  // Company name
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(255, 255, 255)
  doc.text(fitText(doc, company.name || 'Company Name', 90), textX, 13)

  // Email + phone
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(200, 220, 255)
  let infoY = 19
  if (company.email) { doc.text(company.email, textX, infoY); infoY += 5 }
  if (company.phone) doc.text(`Tel: ${company.phone}`, textX, infoY)

  // Right side — date / time / generated by
  doc.setFontSize(7.5)
  doc.setTextColor(220, 235, 255)
  doc.text(date, PAGE_W - MARGIN, 12, { align: 'right' })
  doc.text(time, PAGE_W - MARGIN, 18, { align: 'right' })
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  doc.setTextColor(255, 255, 255)
  doc.text(`Generated by: ${userName || 'System'}`, PAGE_W - MARGIN, 25, { align: 'right' })

  // ── Band 2: document title (white bg, clean) ─────────────────────────────
  const titleY = 34
  doc.setFillColor(255, 255, 255)
  doc.rect(0, titleY, PAGE_W, 18, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...C.darkText)
  doc.text(title.toUpperCase(), MARGIN, titleY + 11)

  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...C.mutedText)
    const subFit = fitText(doc, subtitle, PAGE_W - MARGIN * 2 - doc.getTextWidth(title.toUpperCase()) - 10)
    doc.text(subFit, PAGE_W - MARGIN, titleY + 11, { align: 'right' })
  }

  // Thin accent rule below title band
  doc.setDrawColor(r, g, b)
  doc.setLineWidth(0.6)
  doc.line(0, titleY + 18, PAGE_W, titleY + 18)

  return titleY + 22  // content starts at ~y=74mm from top
}

// ── Draw section label (light bg, NOT dark box) ──────────────────────────────
// Returns next Y after the label
export function sectionLabel(doc, text, y, color = C.indigo) {
  // Light tinted background
  doc.setFillColor(C.sectionBg[0], C.sectionBg[1], C.sectionBg[2])
  doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, 6.5, 'F')
  // Left accent stripe
  doc.setFillColor(...color)
  doc.rect(MARGIN, y, 2.5, 6.5, 'F')
  // Text
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  doc.setTextColor(...color)
  doc.text(text.toUpperCase(), MARGIN + 5, y + 4.5)
  return y + 9
}

// ── Draw footer on every page ────────────────────────────────────────────────
export function drawFooter(doc, { company, title, note = 'Internal Document · Confidential' }) {
  const total = doc.internal.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    doc.setFillColor(...C.sectionBg)
    doc.rect(0, PAGE_H - 9, PAGE_W, 9, 'F')
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.25)
    doc.line(0, PAGE_H - 9, PAGE_W, PAGE_H - 9)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.5)
    doc.setTextColor(...C.mutedText)
    doc.text(note, MARGIN, PAGE_H - 3.5)
    doc.text(`${company || ''} · ${title}`, PAGE_W / 2, PAGE_H - 3.5, { align: 'center' })
    doc.text(`Page ${i} / ${total}`, PAGE_W - MARGIN, PAGE_H - 3.5, { align: 'right' })
  }
}

// ── Receipt image cache ──────────────────────────────────────────────────────

let _receiptHeaderImg = null, _receiptHeaderTried = false
let _receiptFooterImg = null, _receiptFooterTried = false

async function loadStaticImg(path) {
  try {
    const res = await fetch(path)
    if (!res.ok) return null
    const blob = await res.blob()
    return new Promise(resolve => {
      const r = new FileReader()
      r.onload  = () => resolve(r.result)
      r.onerror = () => resolve(null)
      r.readAsDataURL(blob)
    })
  } catch { return null }
}

async function getReceiptHeaderImg() {
  if (!_receiptHeaderTried) { _receiptHeaderTried = true; _receiptHeaderImg = await loadStaticImg('/static/header.jpg') }
  return _receiptHeaderImg
}
async function getReceiptFooterImg() {
  if (!_receiptFooterTried) { _receiptFooterTried = true; _receiptFooterImg = await loadStaticImg('/static/footer.jpg') }
  return _receiptFooterImg
}

// Receipt layout constants
const RECEIPT_HEADER_H = 40   // mm — height of /static/header.jpg
const RECEIPT_FOOTER_H = 22   // mm — height of /static/footer.jpg
const RECEIPT_TITLE_H  = 14   // mm — dark title band below header
export const RECEIPT = {
  HEADER_H:      RECEIPT_HEADER_H,
  FOOTER_H:      RECEIPT_FOOTER_H,
  CONTENT_START: RECEIPT_HEADER_H + RECEIPT_TITLE_H + 3,  // ~57mm
  CONTENT_MAX_Y: PAGE_H - RECEIPT_FOOTER_H - 5,           // ~270mm
  PAGE_NEW_START: 16,
}

/**
 * Draw receipt header image + dark title band on the current (first) page.
 * Returns Y where body content should start.
 */
export async function drawReceiptDocHeader(doc, title, subtitle = '') {
  const img = await getReceiptHeaderImg()
  if (img) {
    try { doc.addImage(img, 'PNG', 0, 0, PAGE_W, RECEIPT_HEADER_H) } catch {}
  } else {
    doc.setFillColor(220, 38, 38)
    doc.rect(0, 0, PAGE_W, RECEIPT_HEADER_H, 'F')
  }
  // Dark title band
  doc.setFillColor(17, 24, 39)
  doc.rect(0, RECEIPT_HEADER_H, PAGE_W, RECEIPT_TITLE_H, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(255, 255, 255)
  doc.text(title.toUpperCase(), MARGIN, RECEIPT_HEADER_H + 9.5)
  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(170, 195, 220)
    doc.text(subtitle, PAGE_W - MARGIN, RECEIPT_HEADER_H + 9.5, { align: 'right' })
  }
  return RECEIPT.CONTENT_START
}

/**
 * Draw receipt footer image on every page (call just before savePDF).
 */
export async function drawReceiptDocFooter(doc) {
  const img = await getReceiptFooterImg()
  const total = doc.internal.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    if (img) {
      try { doc.addImage(img, 'PNG', 0, PAGE_H - RECEIPT_FOOTER_H, PAGE_W, RECEIPT_FOOTER_H) } catch {}
    } else {
      doc.setFillColor(241, 245, 249)
      doc.rect(0, PAGE_H - 10, PAGE_W, 10, 'F')
      doc.setDrawColor(209, 213, 219)
      doc.setLineWidth(0.25)
      doc.line(0, PAGE_H - 10, PAGE_W, PAGE_H - 10)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(6.5)
      doc.setTextColor(107, 114, 128)
      doc.text('Computer Generated Document · Avant Elevators', MARGIN, PAGE_H - 4)
      doc.text(`Page ${i} / ${total}`, PAGE_W - MARGIN, PAGE_H - 4, { align: 'right' })
    }
  }
}

/**
 * Draw a signature box with black background.
 * @param {object} doc       jsPDF instance
 * @param {number} x y w h  position and size in mm
 * @param {string} label     box label, e.g. "TECHNICIAN SIGNATURE"
 * @param {string|null} sigData  base64 PNG data URL (or null)
 * @param {string} name      signatory name
 * @param {string} [desig]   signatory designation
 */
export function drawBlackSignatureBox(doc, x, y, w, h, label, sigData, name, desig) {
  // White box with dark border
  doc.setFillColor(255, 255, 255)
  doc.rect(x, y, w, h, 'F')
  doc.setDrawColor(180, 180, 180)
  doc.setLineWidth(0.4)
  doc.rect(x, y, w, h, 'S')
  // Label at top
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(100, 100, 100)
  doc.text((label || 'SIGNATURE').toUpperCase(), x + 4, y + 5.5)
  // Signature image
  if (sigData) {
    try { doc.addImage(sigData, 'PNG', x + 4, y + 8, w - 8, h - 20) } catch {}
  } else {
    doc.setFontSize(7)
    doc.setTextColor(180, 180, 180)
    doc.text('[ No signature ]', x + w / 2, y + h / 2 - 4, { align: 'center' })
  }
  // Separator line
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.3)
  doc.line(x + 4, y + h - 11, x + w - 4, y + h - 11)
  // Name
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(17, 24, 39)
  doc.text(name || '_______________', x + 4, y + h - 6)
  // Designation
  if (desig) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.5)
    doc.setTextColor(107, 114, 128)
    doc.text(desig, x + 4, y + h - 1.5)
  }
}

// ── Draw 2-column info grid ──────────────────────────────────────────────────
// Returns next Y after the grid
export function infoGrid(doc, pairs, startY) {
  const colW   = (PAGE_W - MARGIN * 2) / 2
  const rowH   = 9
  const maxY   = PAGE_H - 16
  let y = startY
  let col = 0

  pairs.forEach(([label, value], i) => {
    if (y + rowH > maxY) { doc.addPage(); y = 14 }
    const x = MARGIN + col * colW

    // Alternate row shading (per row, pair of cells = same shade)
    if (Math.floor(i / 2) % 2 === 0) {
      doc.setFillColor(...C.rowAlt)
      doc.rect(x, y, colW, rowH, 'F')
    }

    // Label
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(...C.mutedText)
    doc.text(String(label), x + 3, y + 3.5)

    // Value
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(...C.darkText)
    const val = fitText(doc, String(value ?? '—'), colW - 6)
    doc.text(val, x + 3, y + 7.5)

    col = col === 0 ? 1 : 0
    if (col === 0) y += rowH
  })
  if (col !== 0) y += rowH  // finish last odd pair

  return y + 3
}

// ── Get company + user context ───────────────────────────────────────────────
export async function getCompanyAndUser() {
  const { company, load } = useCompanyConfig()
  await load()   // always load fresh from Firestore
  const auth = useAuthStore()
  let contractHtml = ''
  let amcRenewalHtml = ''
  let inspectionHtml = ''
  try {
    const docs = await getAll(Collections.CONFIGURATIONS)
    if (docs.length) {
      const sorted = docs.sort((a, b) => {
        const tsA = a.updatedAt ? new Date(a.updatedAt).getTime() : 0
        const tsB = b.updatedAt ? new Date(b.updatedAt).getTime() : 0
        return tsB - tsA
      })
      contractHtml = sorted[0].contractHtml || ''
      amcRenewalHtml = sorted[0].amcRenewalHtml || ''
      inspectionHtml = sorted[0].inspectionHtml || ''
    }
  } catch { /* non-blocking */ }
  return {
    company: company.value,
    userName: auth.user?.fullName || auth.user?.name || 'System',
    contractHtml,
    amcRenewalHtml,
    inspectionHtml,
  }
}

// ── Table PDF (bulk exports) ─────────────────────────────────────────────────
export async function exportTablePDF({
  title, subtitle = '', columns, rows, filename = 'export',
  orientation = 'portrait', accent, ui,
}) {
  const { company, userName } = await getCompanyAndUser()
  const acc = accent || C.blue

  try {
    const { jsPDF } = await import('jspdf')
    const { applyPlugin } = await import('jspdf-autotable')
    applyPlugin(jsPDF)
    const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' })

    const startY = await drawHeader(doc, {
      company,
      userName,
      title,
      subtitle: subtitle || `${rows.length} record${rows.length !== 1 ? 's' : ''}`,
      accent: acc,
    })

    doc.autoTable({
      startY,
      head: [columns],
      body: rows,
      styles: {
        fontSize: 8, cellPadding: { top: 3, right: 3.5, bottom: 3, left: 3.5 },
        font: 'helvetica', overflow: 'linebreak', textColor: C.darkText,
        minCellHeight: 8,
      },
      headStyles: {
        fillColor: acc, textColor: C.white,
        fontStyle: 'bold', fontSize: 8, halign: 'left',
        minCellHeight: 8,
      },
      alternateRowStyles: { fillColor: C.rowAlt },
      rowPageBreak: 'auto',
      margin: { left: MARGIN, right: MARGIN, bottom: 12 },
      didDrawPage: async (data) => {
        if (data.pageNumber > 1) {
          await drawHeader(doc, { company, userName, title, subtitle: '(continued)', accent: acc })
        }
      },
    })

    drawFooter(doc, { company: company.name, title })
    const { savePDF } = await import('@/utils/saveFile')
    await savePDF(doc, `${filename}.pdf`, ui)
    if (!Capacitor.isNativePlatform()) ui?.success('PDF exported.')
    return true
  } catch (e) {
    console.warn('[PDF]', e)
    ui?.error('PDF export failed: ' + e.message)
    return false
  }
}

// ── Composable (used by vue components) ─────────────────────────────────────
export function usePDF() {
  function formatCurrency(amount) { return toRs(amount) }

  return {
    exportTablePDF,
    formatCurrency,
    // building blocks for custom PDFs
    _drawHeader:        drawHeader,
    _drawFooter:        drawFooter,
    _sectionLabel:      sectionLabel,
    _infoGrid:          infoGrid,
    _toRs:              toRs,
    _C:                 C,
    _MARGIN:            MARGIN,
    _PAGE_W:            PAGE_W,
    _PAGE_H:            PAGE_H,
    _getCtx:            getCompanyAndUser,
    _fitText:           fitText,
    // Receipt-style PDFs (header/footer images + black sig boxes)
    _drawReceiptHeader: drawReceiptDocHeader,
    _drawReceiptFooter: drawReceiptDocFooter,
    _drawBlackSig:      drawBlackSignatureBox,
    _RECEIPT:           RECEIPT,
  }
}
